[project]
name = "content-pipelint-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[tools]>=1.5.0",
    "firecrawl>=4.8.0",
    "python-dotenv>=1.2.1",
]
